# Sorted flags (alphabetically by prefix/type)

ALLOW_MISSING_DEPENDENCIES := true
AB_OTA_PARTITIONS += \
    odm \
    product \
    system \
    system_ext \
    vendor
AB_OTA_UPDATER := true

BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3
BOARD_BOOTIMAGE_PARTITION_SIZE := 100663296
BOARD_BOOT_HEADER_VERSION := 4
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_INCLUDE_KERNEL_FROM_BOOT_IMAGE := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_CMDLINE := androidboot.hardware=qcom androidboot.memcg=1 lpm_levels.sleep_disabled=1 msm_rtb.filter=0x237 service_locator.enable=1 androidboot.usbcontroller=4e00000.dwc3 swiotlb=0 loop.max_part=7 cgroup.memory=nokmem,nosocket iptable_raw.raw_before_defrag=1 ip6table_raw.raw_before_defrag=1 firmware_class.path=/vendor/firmware
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_SUPER_PARTITION_GROUPS := xiaomi_dynamic_partitions
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 100663296
BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST := system system system_ext system_ext product product vendor vendor odm odm
BOARD_XIAOMI_DYNAMIC_PARTITIONS_SIZE := 9122611200
BOARD_USES_METADATA_PARTITION := true
BOARD_USES_QCOM_FBE_DECRYPTION := true

BOOT_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)

DEXPREOPT_GENERATE_APEX_IMAGE := true

DEVICE_PATH := device/xiaomi/stone

FOX_VIRTUAL_AB_DEVICE := 1

LZMA_COMPRESSION := -9
LZMA_RAMDISK_TARGETS := vendor_boot

OF_CLOCK_POS := 1
OF_FLASHLIGHT_ENABLE := 0
OF_HIDE_NOTCH := 1
OF_IGNORE_LOGICAL_MOUNT_ERRORS := 1
OF_MAINTAINER := Himelpvz
OF_SCREEN_H := 2400
OF_STATUS_H := 100
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_USE_GREEN_LED := 0

PLATFORM_SECURITY_PATCH := 2099-12-31
PLATFORM_VERSION := 99.87.36
PLATFORM_VERSION_LAST_STABLE := $(PLATFORM_VERSION)

RECOVERY_SDCARD_ON_DATA := true

SHRP_AB := true
SHRP_ALT_REBOOT := true
SHRP_CUSTOM_FLASHLIGHT := true
SHRP_DEVICE_CODE := stone
SHRP_DEVICE_TYPE := A/B
SHRP_DARK := true
SHRP_EDL_MODE := 0
SHRP_EXPRESS := true
SHRP_EXTERNAL := /external_sd
SHRP_FLASH := 1
SHRP_FLASH_MAX_BRIGHTNESS := 1
SHRP_FONP_1 := /sys/devices/virtual/camera/flash/rear_flash 
SHRP_INTERNAL := /sdcard
SHRP_MAINTAINER := Himel_Pvz
SHRP_OFFICIAL := false
SHRP_OTG := /usb_otg
SHRP_PATH := device/xiaomi/stone
SHRP_REC := /dev/block/bootdevice/by-name/vendor_boot
SHRP_REC_TYPE := Treble
SHRP_STATUSBAR_LEFT_PADDING := 40
SHRP_STATUSBAR_RIGHT_PADDING := 40

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a55
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_BOARD_PLATFORM := holi
TARGET_BOOTLOADER_BOARD_NAME := holi
TARGET_COPY_OUT_VENDOR := vendor
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a76
TARGET_KERNEL_CONFIG := stone_defconfig
TARGET_KERNEL_SOURCE := kernel/xiaomi/stone
TARGET_NO_BOOTLOADER := true
TARGET_NO_RECOVERY := true
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_USES_LOGD := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

TW_BACKUP_EXCLUSIONS := /data/fonts
TW_BATTERY_SYSFS_WAIT_SECONDS := 5
TW_BRIGHTNESS_PATH := "/sys/class/backlight/panel0-backlight/brightness"
TW_CUSTOM_BATTERY_POS := "790"
TW_CUSTOM_CLOCK_POS := "50"
TW_CUSTOM_CPU_POS := "250"
TW_CUSTOM_CPU_TEMP_PATH := "/sys/class/thermal/thermal_zone28/temp"
TW_DEFAULT_BRIGHTNESS := 200
TW_DEVICE_VERSION := HPS_TWRP
TW_EXCLUDE_APEX := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_EXTRA_LANGUAGES := true
TW_FRAMERATE := 60
TW_HAS_EDL_MODE := false
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
TW_INCLUDE_LIBRESETPROP := true
TW_INCLUDE_NTFS_3G := true
TW_INCLUDE_REPACKTOOLS := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_LOAD_VENDOR_MODULES := "adsp_loader_dlkm.ko"
TW_MAX_BRIGHTNESS := 2047
TW_NO_SCREEN_BLANK := true
TW_STATUS_ICONS_ALIGN := center
TW_THEME := portrait_hdpi
TW_USE_FSCRYPT_POLICY := 2
TW_USE_TOOLBOX := true

TWRP_INCLUDE_LOGCAT := true

VENDOR_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)
